name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Copy.env.example to .env
      run: cp ./miguapa-mundi/.env.example ./miguapa-mundi/.env
    - name: Replace env credentials
      run: | 
        sed -i "s/APP_NAME=Laravel.*/APP_NAME=${{ secrets.APP_NAME }}/g" ./miguapa-mundi/.env
        sed -i "s/DB_HOST=127.0.0.1.*/DB_HOST=${{ secrets.DB_HOST }}/g" ./miguapa-mundi/.env
        sed -i "s/DB_DATABASE=laravel.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/g" ./miguapa-mundi/.env
        sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g" ./miguapa-mundi/.env
        sed -i "s/MAIL_MAILER=smtp.*/MAIL_MAILER=${{ secrets.MAIL_MAILER }}/g" ./miguapa-mundi/.env
        sed -i "s/MAIL_HOST=mailpit.*/MAIL_HOST=${{ secrets.MAIL_HOST }}/g" ./miguapa-mundi/.env
        sed -i "s/MAIL_PORT=1025.*/MAIL_PORT=${{ secrets.MAIL_PORT }}/g" ./miguapa-mundi/.env
        sed -i "s/MAIL_USERNAME=null.*/MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}/g" ./miguapa-mundi/.env
        sed -i "s/MAIL_PASSWORD=null.*/MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}/g" ./miguapa-mundi/.env
        sed -i "s/MAIL_ENCRYPTION=null.*/MAIL_ENCRYPTION=${{ secrets.MAIL_ENCRYPTION }}/g" ./miguapa-mundi/.env
        sed -i "s/MAIL_FROM_ADDRESS="hello@example.com".*/MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}/g" ./miguapa-mundi/.env
        sed -i "s/GOOGLE_MAPS_API_KEY=.*/GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}/g" ./miguapa-mundi/.env
        sed -i "s/NEWS_API_KEY=.*/NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}/g" ./miguapa-mundi/.env
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
      
    - name: Build the Docker image
      run: docker build ./miguapa-mundi --file Dockerfile --tag juanfepi27/miguapa-mundi:latest
      
    - name: Docker Push
      run: docker push juanfepi27/miguapa-mundi
